### ISSUE TITLE
clarify location of source_characteristics.csv

### ISSUE THREAD

**Issue by regnans** [TESTgroup-BNL/CSVQA#4]
Working through the README, Step 1. 

Took me a while to find this file - should there be a template copy in an easy to find place on the repo? 
Then, unclear if I should create a data/2019 folder in the repo to store the updated source_characteristics file in.

**Comment by amcmahon01** [comment]
Yes, there should be a easier to find template file.  (For ZPW data, the one for 2018 will work.)  It ended up in data/2018 by itself because I didn't upload the other 2018 data to github.  Anything dataset specific probably shouldn't be in the repo, but I included it to serve as a functional template.  Ultimately, the repo data directory could be removed or filled with a complete example from a single year, which was my original intention.

The source_characteristics.csv file to be used should be in the data source directory (specified in [the config file](https://github.com/TESTgroup-BNL/CSVQA/blob/master/src/default.conf)).

**Comment by regnans** [comment]
thanks. this is clearer now (and perhaps should have been obvious to me). No new files in the repo.
