### ISSUE TITLE
more on file locations partly overwrites previous issue)

### ISSUE THREAD

**Issue by regnans** [TESTgroup-BNL/CSVQA#5]
So ... is it correct that I copy the raw data .dat files, the .conf and the source_characteristics.csv into a directory (e.g. \\dc3.bnl.gov\bnlfiles\Test\Projects\NGEE-Arctic\ZPW\2019\Data\QA) and then run from there?

**Comment by amcmahon01** [comment]
Yes, with a couple clarifications.  You could put everything (script, config, source data, source characteristics) into one directory and have the output generated there and it would work fine, but there are some other possible options.

You could configure up to three directories for a single run:
- Script directory (includes .py and .conf files)
    The configuration file must be in the same directory as the python script.

- Input (data source files, including source_characteristics.csv)
    The source characteristics file must be in the same directory as the source data.

- Output (data output files)
    By default this is the same as the input directory.

Given how small the scripts and config file are, I would recommend copying them directly into what will be your output directory, so that there is never any question as to how that data was generated.  (If you're using a separate source directory, I'd copy source_characteristics.csv to the output folder too.)

**Comment by regnans** [comment]
Having Input (raw) and Output (QA) directories makes sense to me. 
I am not clear on where the Input directory is specified. Not obvious in the zpw_2018.conf example. 
I have copied the scripts and files to 2019/data/QA (and the source_characteristics into data/raw).

**Comment by amcmahon01** [comment]
The input is specified on lines 8 and 9 of the [config file](https://github.com/TESTgroup-BNL/CSVQA/blob/master/src/default.conf), as fpath and inputFile.  In zpw_2018.conf, "fpath = ..\" is saying to use the parent directory.  (I originally ran this in a local directory "2018\Data\Season\QA" and the raw data was in "2018\Data\Season".)  Feel free to reorganize as you see fit.  (Also, don't mind the backslashes, I actually ran it on my Windows laptop rather than the TEST server.)  You can use relative or absolute paths for fpath.  So if you were running the script in 2019\Data\QA and the data was in 2019\Data\Raw, you could use "fpath = ..\Raw\\" (or ../Raw/ on the server).

**Comment by regnans** [comment]
Updated the conf to  "fpath = ../Raw/". Success in finding the files!
